name: mmaction2_dev
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pytorch::pytorch==2.0.1
  - pytorch::torchvision==0.15.2
  - pytorch::torchaudio==2.0.2
  - pytorch-cuda=11.8
  - pandas
  - numpy
  - scipy
  - matplotlib
  - networkx
  - pillow
  - pip
  - pip:
    - pip>=23.2
    - mmcv==2.1.0
    - mmdet==3.3.0
    - mmengine==0.10.7
    - mmpose==1.3.2
    - openmim==0.3.9
    - decord==0.6.0
    - opencv-contrib-python==4.12.0.88
    - pycocotools==2.0.7
    - xtcocotools==1.14.3
    - addict==2.4.0
    - einops==0.8.1
    - chumpy==0.70
    - shapely==2.0.7
    - pyyaml>=6.0
    - tqdm>=4.65
    - requests>=2.28
    - rich>=13.4
    - yapf>=0.43
    - markdown>=3.7
    - cython>=3.1
